[req]
distinguished_name = req_distinguished_name
req_extensions = req_ext

[req_distinguished_name]

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1 = am.wso2.com
DNS.2 = gw.wso2.com
DNS.3 = websocket.wso2.com
DNS.4 = websub.wso2.com
DNS.5 = km.wso2.com

