kubernetes:
  ingressClass: "nginx"

  # 1. Activation de l'Ingress NGINX classique
  ingress:
    tlsSecret: "wso2-am-tls-cert"

    management:
      enabled: true
      hostname: "am.wso2.com"
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/affinity: "cookie"
        nginx.ingress.kubernetes.io/session-cookie-name: "route"
        nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"

    gateway:
      enabled: true
      hostname: "gw.wso2.com"
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"

    websocket:
      enabled: false

    websub:
      enabled: false

  # 2. Désactivation explicite de Gateway API (supprime les HTTPRoutes)
  gatewayAPI:
    enabled: false

image:
  registry: "docker.io"
  repository: "wso2/wso2am"
  tag: "4.7.0"
  imagePullPolicy: Always
