apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wso2
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "CHANGE_ME_ROOT_PASSWORD"
  MYSQL_DATABASE: "apim_db"
  MYSQL_USER: "wso2carbon"
  MYSQL_PASSWORD: "CHANGE_ME_PASSWORD"
