apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:

  name: protect-apim-namespace


spec:

  validationFailureAction: Enforce

  background: false


  rules:

  - name: protect-apim-deletion


    match:

      any:

      - resources:

          kinds:

          - Namespace


    validate:

      message: "Le namespace apim est protégé."

      deny:

        conditions:

          any:

          - key: "{{ request.object.metadata.name }}"

            operator: Equals

            value: apim
