apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: require-image-pull-policy

spec:
  validationFailureAction: Enforce
  background: true

  rules:

  - name: validate-image-pull-policy

    match:
      any:
      - resources:
          kinds:
          - Pod

    validate:
      message: "imagePullPolicy doit être Always ou IfNotPresent."

      foreach:
      - list: "request.object.spec.containers"

        deny:
          conditions:
            any:
            - key: "{{ element.imagePullPolicy }}"
              operator: Equals
              value: Never
