apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-secret-admin
spec:
  validationFailureAction: Enforce
  background: false

  rules:
  - name: block-admin-secret
    match:
      any:
      - resources:
          kinds:
            - Secret
          operations:
            - CREATE
            - UPDATE

    validate:
      message: "L'utilisateur/mot de passe 'admin' en clair est interdit dans un Secret."
      deny:
        conditions:
          any:
          - key: "{{ request.object.stringData.adminUsername || '' }}"
            operator: Equals
            value: "admin"
          - key: "{{ request.object.stringData.adminPassword || '' }}"
            operator: Equals
            value: "admin"
          - key: "{{ base64_decode(request.object.data.adminUsername || 'Cg==') }}"
            operator: Equals
            value: "admin"
          - key: "{{ base64_decode(request.object.data.adminPassword || 'Cg==') }}"
            operator: Equals
            value: "admin"
