apiVersion: v1
kind: PersistentVolume
metadata:
  name: wso2-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/wso2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2-pvc
  namespace: wso2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
